name: "Feature Request"
description: Create a new ticket for a new feature request
title: "[REQUEST] - <title>"
labels: [
    "question"
]
body:
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: Provide a brief explanation of the feature.
      placeholder: Describe in a few lines your feature request.
    validations:
      required: true
  - type: textarea
    id: basic_example
    attributes:
      label: "Basic Example"
      description: Indicate here some basic examples of your feature.
      placeholder: A few specific words about your feature request.
    validations:
      required: true
  - type: textarea
    id: drawbacks
    attributes:
      label: "Why"
      description: Why you want to see this feature added?
      placeholder: How would this feature be benefitial for Machine.
    validations:
      required: true
  - type: textarea
    id: unresolved_question
    attributes:
      label: "Unresolved questions"
      description: What questions still remain unresolved?
      placeholder: Identify any unresolved issues.
    validations:
      required: false