/*
 * This file is part of Machine.
 *
 * Machine is free software: you can redistribute it and/or modify it under the terms of the
 * GNU General Public License as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later version.
 *
 * Machine is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Machine.
 * If not, see <https://www.gnu.org/licenses/>.
 */
package org.machinemc.api.world.generation;

import org.machinemc.api.world.biomes.Biome;
import org.machinemc.api.world.blocks.BlockType;
import org.machinemc.nbt.NBTCompound;

/**
 * Represents a section with content generated by a world generator.
 */
public interface GeneratedSection {

    int BLOCK_DATA_SIZE = 16 * 16 * 16;
    int BIOME_DATA_SIZE = 4 * 4 * 4;

    /**
     * @return palette of this section generated by the chunk
     */
    BlockType[] getBlockPalette();

    /**
     * Block data of this section, values need to match the palette indices of
     * block types.
     * <p>
     * For index encoding and decoding use {@link org.machinemc.api.chunk.Section#index(int, int, int)}
     * and {@link org.machinemc.api.chunk.Section#decode(int)}.
     * <p>
     * For specifying data of individual generated blocks {@link GeneratedSection#getTileEntitiesData()} is used.
     * @return block data
     * @apiNote size has to be {@link GeneratedSection#BLOCK_DATA_SIZE}
     */
    short[] getBlockData();

    /**
     * @return biome palette of this section generated by the chunk
     */
    Biome[] getBiomePalette();

    /**
     * Biome data of this section, values need to match the palette indices of
     * biomes.
     * <p>
     * For index encoding and decoding use {@link org.machinemc.api.chunk.Section#index(int, int, int)}
     * and {@link org.machinemc.api.chunk.Section#decode(int)}.
     * @return biome data
     * @apiNote size has to be {@link GeneratedSection#BIOME_DATA_SIZE}
     */
    short[] getBiomeData();

    /**
     * Used for generating of tile entities, indices of the array need to match encoding positions
     * using {@link org.machinemc.api.chunk.Section#index(int, int, int)}.
     * <p>
     * NBT Compounds provided by will merge to initialized compounds of the blocks. Block type
     * mapped to the same position has to be a tile entity {@link org.machinemc.api.world.blocks.BlockEntityType}
     * @return nbt of tile entities generated in the section
     * @apiNote size has to be {@link GeneratedSection#BLOCK_DATA_SIZE}
     */
    NBTCompound[] getTileEntitiesData();

}
