package org.machinemc.server.exception;

import lombok.Getter;
import org.machinemc.server.network.ClientConnection;
import org.jetbrains.annotations.NotNull;

/**
 * Represents an exception generated by client while being on the server.
 */
public class ClientException extends RuntimeException {

    @Getter
    private final @NotNull ClientConnection connection;

    public ClientException(@NotNull ClientConnection connection) {
        super();
        this.connection = connection;
    }

    public ClientException(@NotNull ClientConnection connection, @NotNull String message) {
        super(message);
        this.connection = connection;
    }

    public ClientException(@NotNull ClientConnection connection, @NotNull String message, @NotNull Throwable cause) {
        super(message, cause);
        this.connection = connection;
    }

    public ClientException(@NotNull ClientConnection connection, @NotNull Throwable cause) {
        super(cause);
        this.connection = connection;
    }

}
